export * from './Regis.jsx';
export * from './SignIn.jsx';
export * from './Dashboard.jsx';
export * from './Inventaris.jsx';
export * from './Sparepart.jsx';
export * from './Transaksi.jsx';
export * from './Laporan.jsx';
export * from './LaporanMekanik.jsx';
export * from './About.jsx';
